// Generated by scripts/sync-chat-app-model.mjs.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OntologyError = exports.SOURCE_ONTOLOGY_ENTITY = void 0;
exports.ontologyEntities = ontologyEntities;
exports.ontologyAttributeAccepts = ontologyAttributeAccepts;
exports.validatePersonaOntology = validatePersonaOntology;
exports.validateOntologyReferenceShape = validateOntologyReferenceShape;
exports.validateOntologyReference = validateOntologyReference;
exports.validateOntologyOutput = validateOntologyOutput;
/** Logical metadata only. Authentication references name slots, never credential values. */
exports.SOURCE_ONTOLOGY_ENTITY = {
    type: 'Source', description: 'A place where information can be obtained. Instances live in a persona/user-scoped source registry List.',
    attributes: {
        id: { type: 'string', required: true }, name: { type: 'string', required: true }, type: { type: 'string' },
        provider: { type: 'string' }, url: { type: 'string', required: true }, supportedRegions: { type: 'array' },
        supportedLanguages: { type: 'array' }, capabilities: { type: 'array' }, dataTypes: { type: 'array' },
        accessMethod: { type: 'string', enum: ['browser', 'api', 'mcp', 'provider'] }, connectorReference: { type: 'string' },
        authenticationReference: { type: 'string' }, freshness: { type: 'string', enum: ['fresh', 'stale', 'unknown'] },
        qualityScore: { type: 'number' }, reliabilityScore: { type: 'number' }, coverageScore: { type: 'number' },
        lastCheckedAt: { type: 'datetime' }, status: { type: 'string', enum: ['candidate', 'active', 'inactive'] }, provenance: { type: 'object' }
    }
};
function ontologyEntities(ontology) {
    return [...(ontology.primitives?.includes('Source') ? [exports.SOURCE_ONTOLOGY_ENTITY] : []), ...ontology.entities];
}
class OntologyError extends Error {
    constructor(code, message) {
        super(message);
        this.code = code;
        this.status = 422;
    }
}
exports.OntologyError = OntologyError;
const fail = (message) => { throw new OntologyError('INVALID_ONTOLOGY', message); };
const identifier = (value) => typeof value === 'string' && /^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(value) && !['constructor', 'prototype', '__proto__'].includes(value);
function object(value, label) {
    if (!value || Array.isArray(value) || typeof value !== 'object' || Object.getPrototypeOf(value) !== Object.prototype)
        fail(`${label} must be an object.`);
    return value;
}
function keys(value, allowed, label) {
    if (Object.keys(value).some(key => !allowed.includes(key)))
        fail(`${label} contains an unsupported field.`);
}
function text(value, label, max = 2000) {
    if (value !== undefined && (typeof value !== 'string' || !value.trim() || value.length > max))
        fail(`Invalid ${label}.`);
}
function ontologyAttributeAccepts(attribute, value) {
    if (value === null)
        return attribute.nullable === true;
    let valid = false;
    switch (attribute.type) {
        case 'string':
            valid = typeof value === 'string';
            break;
        case 'number':
            valid = typeof value === 'number' && Number.isFinite(value);
            break;
        case 'integer':
            valid = Number.isSafeInteger(value);
            break;
        case 'boolean':
            valid = typeof value === 'boolean';
            break;
        case 'array':
            valid = Array.isArray(value);
            break;
        case 'object':
            valid = Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype);
            break;
        case 'date':
            valid = typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value;
            break;
        case 'datetime':
            valid = typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(value) && Number.isFinite(Date.parse(value));
            break;
    }
    return valid && (!attribute.enum || attribute.enum.includes(value));
}
/** Pure validation shared by runtime and the portable coding-agent validator. */
function validatePersonaOntology(value) {
    const d = object(value, 'Ontology');
    keys(d, ['schemaVersion', 'resourceKey', 'version', 'name', 'status', 'description', 'entities', 'relationships', 'primitives'], 'Ontology');
    if (d.schemaVersion !== 1 || typeof d.resourceKey !== 'string' || !/^ontology\.persona\.[a-z0-9][a-z0-9.-]{0,100}$/.test(d.resourceKey))
        fail('Use schemaVersion 1 and an ontology.persona.* resourceKey.');
    if (typeof d.version !== 'string' || !/^\d+\.\d+\.\d+$/.test(d.version))
        fail('Use a semantic version, such as 0.1.0.');
    if (!['placeholder', 'defined'].includes(d.status) || typeof d.name !== 'string')
        fail('Name and definition status are required.');
    text(d.name, 'name', 120);
    text(d.description, 'description');
    if (!Array.isArray(d.entities) || d.entities.length > 200 || !Array.isArray(d.relationships) || d.relationships.length > 400)
        fail('Declare entities and relationships within the size limits.');
    if (d.primitives !== undefined && (!Array.isArray(d.primitives) || d.primitives.length > 1 || d.primitives.some((value) => value !== 'Source')))
        fail('Only declared shared ontology primitives are supported.');
    const entities = new Set(d.primitives?.includes('Source') ? ['Source'] : []);
    const relationships = new Set();
    for (const raw of d.entities) {
        const entity = object(raw, 'Entity');
        keys(entity, ['type', 'description', 'attributes'], 'Entity');
        if (!identifier(entity.type) || entities.has(entity.type))
            fail('Entity types must be unique stable identifiers.');
        entities.add(entity.type);
        text(entity.description, 'entity description');
        const attributes = object(entity.attributes, 'Attributes');
        if (Object.keys(attributes).length > 200)
            fail('Use at most 200 attributes per entity.');
        for (const [key, rawAttribute] of Object.entries(attributes)) {
            if (!identifier(key))
                fail('Attribute names must be stable identifiers.');
            const a = object(rawAttribute, 'Attribute');
            keys(a, ['type', 'description', 'required', 'nullable', 'enum'], 'Attribute');
            if (!['string', 'number', 'integer', 'boolean', 'object', 'array', 'date', 'datetime'].includes(a.type))
                fail('Invalid attribute type.');
            text(a.description, 'attribute description');
            for (const flag of ['required', 'nullable'])
                if (a[flag] !== undefined && typeof a[flag] !== 'boolean')
                    fail(`Invalid ${flag} flag.`);
            if (a.enum !== undefined && (!Array.isArray(a.enum) || !a.enum.length || a.enum.length > 100 || a.enum.some((entry) => !['string', 'number', 'boolean'].includes(typeof entry) || !ontologyAttributeAccepts({ type: a.type }, entry))))
                fail('Enum values must match the attribute type.');
        }
    }
    for (const raw of d.relationships) {
        const r = object(raw, 'Relationship');
        keys(r, ['type', 'from', 'to', 'direction', 'description', 'cardinality'], 'Relationship');
        if (!identifier(r.type) || relationships.has(r.type) || !entities.has(r.from) || !entities.has(r.to) || !['directed', 'undirected'].includes(r.direction))
            fail('Relationships need unique types, known endpoints, and a direction.');
        relationships.add(r.type);
        text(r.description, 'relationship description');
        if (r.cardinality !== undefined) {
            const c = object(r.cardinality, 'Cardinality');
            keys(c, ['from', 'to', 'minTargets', 'maxTargets'], 'Cardinality');
            if (!['one', 'many'].includes(c.from) || !['one', 'many'].includes(c.to))
                fail('Cardinality uses one or many.');
            for (const key of ['minTargets', 'maxTargets'])
                if (c[key] !== undefined && (!Number.isSafeInteger(c[key]) || c[key] < 0))
                    fail('Cardinality bounds must be nonnegative integers.');
            if (c.minTargets !== undefined && c.maxTargets !== undefined && c.minTargets > c.maxTargets || c.to === 'one' && (c.minTargets > 1 || c.maxTargets > 1))
                fail('Inconsistent cardinality bounds.');
        }
    }
    return d;
}
function validateOntologyReferenceShape(value) {
    const r = object(value, 'Ontology reference');
    keys(r, ['entityType', 'ontologyVersion', 'recordsPath', 'fields'], 'Ontology reference');
    if (!identifier(r.entityType) || typeof r.recordsPath !== 'string')
        fail('Declare an entity type and recordsPath.');
    if (r.ontologyVersion !== undefined && (typeof r.ontologyVersion !== 'string' || !/^\d+\.\d+\.\d+$/.test(r.ontologyVersion)))
        fail('Invalid ontology version.');
    const fields = object(r.fields, 'Ontology field references');
    if (!Object.keys(fields).length || Object.keys(fields).length > 200)
        fail('Reference 1 to 200 ontology attributes.');
    pointerSegments(r.recordsPath);
    for (const [field, pointer] of Object.entries(fields)) {
        if (!identifier(field))
            fail('Invalid ontology attribute reference.');
        pointerSegments(pointer);
    }
    return r;
}
function validateOntologyReference(ontology, value) {
    const reference = validateOntologyReferenceShape(value);
    if (reference.ontologyVersion && ontology.version !== reference.ontologyVersion)
        throw new OntologyError('ONTOLOGY_VERSION_MISMATCH', 'The feed requires a different persona ontology version.');
    const entity = ontologyEntities(ontology).find(entity => entity.type === reference.entityType);
    if (!entity)
        throw new OntologyError('UNKNOWN_ENTITY_TYPE', 'The persona ontology does not define this entity type.');
    if (Object.keys(reference.fields).some(field => !Object.prototype.hasOwnProperty.call(entity.attributes, field)))
        throw new OntologyError('UNKNOWN_ENTITY_ATTRIBUTE', 'The persona ontology does not define a referenced attribute.');
    return reference;
}
function pointerSegments(value) {
    if (typeof value !== 'string' || value.length > 2000 || value !== '' && !value.startsWith('/') || /~(?![01])/.test(String(value)))
        fail('Use a valid JSON pointer.');
    const parts = value === '' ? [] : value.slice(1).split('/').map(key => key.replace(/~1/g, '/').replace(/~0/g, '~'));
    if (parts.some(key => ['__proto__', 'constructor', 'prototype'].includes(key)))
        fail('Unsafe JSON pointer.');
    return parts;
}
function atPointer(value, path) {
    return pointerSegments(path).reduce((parent, key) => parent && typeof parent === 'object' && Object.prototype.hasOwnProperty.call(parent, key) ? parent[key] : undefined, value);
}
/** Validate a projection without rewriting JSON, coercing types, or persisting instances. */
function validateOntologyOutput(ontology, reference, output) {
    validateOntologyReference(ontology, reference);
    const entity = ontologyEntities(ontology).find(entity => entity.type === reference.entityType);
    const selected = atPointer(output, reference.recordsPath);
    if (selected === undefined)
        throw new OntologyError('ONTOLOGY_OUTPUT_MISMATCH', 'The declared ontology result path is missing.');
    const rows = Array.isArray(selected) ? selected : [selected];
    for (const row of rows)
        for (const [field, path] of Object.entries(reference.fields)) {
            const value = atPointer(row, path);
            const attribute = entity.attributes[field];
            if (value === undefined && !attribute.required)
                continue;
            if (!ontologyAttributeAccepts(attribute, value))
                throw new OntologyError('ONTOLOGY_OUTPUT_MISMATCH', 'Feed JSON does not match its declared ontology attribute types.');
        }
}
