// Generated by scripts/sync-chat-app-model.mjs.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.cloneOntology = exports.OntologyError = exports.SOURCE_ONTOLOGY_ENTITY = void 0;
exports.ontologyEntities = ontologyEntities;
exports.ontologyAttributeAccepts = ontologyAttributeAccepts;
exports.validatePersonaOntology = validatePersonaOntology;
exports.materializeOntology = materializeOntology;
exports.resolveOntology = resolveOntology;
exports.ontologyScopeSelection = ontologyScopeSelection;
exports.allOntologySelections = allOntologySelections;
exports.validateOntologyReferenceShape = validateOntologyReferenceShape;
exports.validateOntologyReference = validateOntologyReference;
exports.validateOntologyOutput = validateOntologyOutput;
const context_selection_cjs_1 = require("./context-selection.cjs");
/** Logical metadata only. Authentication references name slots, never credential values. */
exports.SOURCE_ONTOLOGY_ENTITY = {
    type: 'Source', description: 'A place where information can be obtained. Instances live in a persona/user-scoped source registry List.',
    attributes: {
        id: { type: 'string', required: true }, name: { type: 'string', required: true }, type: { type: 'string' },
        provider: { type: 'string' }, url: { type: 'string', required: true }, supportedRegions: { type: 'array' },
        supportedLanguages: { type: 'array' }, capabilities: { type: 'array' }, dataTypes: { type: 'array' },
        accessMethod: { type: 'string', enum: ['browser', 'api', 'mcp', 'provider'] }, connectorReference: { type: 'string' },
        authenticationReference: { type: 'string' }, freshness: { type: 'string', enum: ['fresh', 'stale', 'unknown'] },
        qualityScore: { type: 'number' }, reliabilityScore: { type: 'number' }, coverageScore: { type: 'number' },
        lastCheckedAt: { type: 'datetime' }, status: { type: 'string', enum: ['candidate', 'active', 'inactive'] }, provenance: { type: 'object' }
    }
};
function ontologyEntities(ontology) {
    return [...(ontology.primitives?.includes('Source') ? [exports.SOURCE_ONTOLOGY_ENTITY] : []), ...ontology.entities];
}
class OntologyError extends Error {
    constructor(code, message) {
        super(message);
        this.code = code;
        this.status = 422;
    }
}
exports.OntologyError = OntologyError;
const fail = (message) => { throw new OntologyError('INVALID_ONTOLOGY', message); };
const identifier = (value) => typeof value === 'string' && /^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(value) && !['constructor', 'prototype', '__proto__'].includes(value);
function object(value, label) {
    if (!value || Array.isArray(value) || typeof value !== 'object' || Object.getPrototypeOf(value) !== Object.prototype)
        fail(`${label} must be an object.`);
    return value;
}
function keys(value, allowed, label) {
    if (Object.keys(value).some(key => !allowed.includes(key)))
        fail(`${label} contains an unsupported field.`);
}
function text(value, label, max = 2000) {
    if (value !== undefined && (typeof value !== 'string' || !value.trim() || value.length > max))
        fail(`Invalid ${label}.`);
}
function ontologyAttributeAccepts(attribute, value) {
    if (value === null)
        return attribute.nullable === true;
    let valid = false;
    switch (attribute.type) {
        case 'string':
            valid = typeof value === 'string';
            break;
        case 'number':
            valid = typeof value === 'number' && Number.isFinite(value);
            break;
        case 'integer':
            valid = Number.isSafeInteger(value);
            break;
        case 'boolean':
            valid = typeof value === 'boolean';
            break;
        case 'array':
            valid = Array.isArray(value);
            break;
        case 'object':
            valid = Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype);
            break;
        case 'date':
            valid = typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value;
            break;
        case 'datetime':
            valid = typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(value) && Number.isFinite(Date.parse(value));
            break;
    }
    return valid && (!attribute.enum || attribute.enum.includes(value));
}
/** Pure validation shared by runtime and the portable coding-agent validator. */
function validatePersonaOntology(value) {
    const d = object(value, 'Ontology');
    keys(d, ['schemaVersion', 'resourceKey', 'version', 'name', 'status', 'description', 'entities', 'relationships', 'primitives', 'localization'], 'Ontology');
    if (d.schemaVersion !== 1 || typeof d.resourceKey !== 'string' || !/^ontology\.persona\.[a-z0-9][a-z0-9.-]{0,100}$/.test(d.resourceKey))
        fail('Use schemaVersion 1 and an ontology.persona.* resourceKey.');
    if (typeof d.version !== 'string' || !/^\d+\.\d+\.\d+$/.test(d.version))
        fail('Use a semantic version, such as 0.1.0.');
    if (!['placeholder', 'defined'].includes(d.status) || typeof d.name !== 'string')
        fail('Name and definition status are required.');
    text(d.name, 'name', 120);
    text(d.description, 'description');
    if (!Array.isArray(d.entities) || d.entities.length > 200 || !Array.isArray(d.relationships) || d.relationships.length > 400)
        fail('Declare entities and relationships within the size limits.');
    if (d.primitives !== undefined && (!Array.isArray(d.primitives) || d.primitives.length > 1 || d.primitives.some((value) => value !== 'Source')))
        fail('Only declared shared ontology primitives are supported.');
    const entities = new Set(d.primitives?.includes('Source') ? ['Source'] : []);
    const relationships = new Set();
    for (const raw of d.entities) {
        const entity = object(raw, 'Entity');
        keys(entity, ['type', 'description', 'attributes'], 'Entity');
        if (!identifier(entity.type) || entities.has(entity.type))
            fail('Entity types must be unique stable identifiers.');
        entities.add(entity.type);
        text(entity.description, 'entity description');
        const attributes = object(entity.attributes, 'Attributes');
        if (Object.keys(attributes).length > 200)
            fail('Use at most 200 attributes per entity.');
        for (const [key, rawAttribute] of Object.entries(attributes)) {
            if (!identifier(key))
                fail('Attribute names must be stable identifiers.');
            const a = object(rawAttribute, 'Attribute');
            keys(a, ['type', 'description', 'required', 'nullable', 'enum'], 'Attribute');
            if (!['string', 'number', 'integer', 'boolean', 'object', 'array', 'date', 'datetime'].includes(a.type))
                fail('Invalid attribute type.');
            text(a.description, 'attribute description');
            for (const flag of ['required', 'nullable'])
                if (a[flag] !== undefined && typeof a[flag] !== 'boolean')
                    fail(`Invalid ${flag} flag.`);
            if (a.enum !== undefined && (!Array.isArray(a.enum) || !a.enum.length || a.enum.length > 100 || a.enum.some((entry) => !['string', 'number', 'boolean'].includes(typeof entry) || !ontologyAttributeAccepts({ type: a.type }, entry))))
                fail('Enum values must match the attribute type.');
        }
    }
    for (const raw of d.relationships) {
        const r = object(raw, 'Relationship');
        keys(r, ['type', 'from', 'to', 'direction', 'description', 'cardinality'], 'Relationship');
        if (!identifier(r.type) || relationships.has(r.type) || !entities.has(r.from) || !entities.has(r.to) || !['directed', 'undirected'].includes(r.direction))
            fail('Relationships need unique types, known endpoints, and a direction.');
        relationships.add(r.type);
        text(r.description, 'relationship description');
        if (r.cardinality !== undefined) {
            const c = object(r.cardinality, 'Cardinality');
            keys(c, ['from', 'to', 'minTargets', 'maxTargets'], 'Cardinality');
            if (!['one', 'many'].includes(c.from) || !['one', 'many'].includes(c.to))
                fail('Cardinality uses one or many.');
            for (const key of ['minTargets', 'maxTargets'])
                if (c[key] !== undefined && (!Number.isSafeInteger(c[key]) || c[key] < 0))
                    fail('Cardinality bounds must be nonnegative integers.');
            if (c.minTargets !== undefined && c.maxTargets !== undefined && c.minTargets > c.maxTargets || c.to === 'one' && (c.minTargets > 1 || c.maxTargets > 1))
                fail('Inconsistent cardinality bounds.');
        }
    }
    if (d.localization !== undefined)
        validateOntologyLocalization(d);
    return d;
}
function validateOntologyLocalization(ontology) {
    const l = object(ontology.localization, 'Localization');
    if (JSON.stringify(l).length > 2000000)
        fail('Ontology localization exceeds the 2 MB limit.');
    keys(l, ['sourceLanguage', 'definition', 'translations', 'variants', 'regions', 'personalizations'], 'Localization');
    const lang = (value) => {
        try {
            if (typeof value !== 'string' || (0, context_selection_cjs_1.contextLanguage)(value) !== value)
                fail('Use canonical BCP 47 language tags.');
        }
        catch {
            fail('Use canonical BCP 47 language tags.');
        }
    };
    lang(l.sourceLanguage);
    if (!Array.isArray(l.regions) || l.regions.length > 100 || !Array.isArray(l.personalizations) || l.personalizations.length > 100)
        fail('Declare at most 100 regions and audiences.');
    const scopeKey = (value) => typeof value === 'string' && /^[a-z0-9][a-z0-9_-]{0,63}$/.test(value) && !['constructor', 'prototype', '__proto__'].includes(value);
    const model = (value) => {
        const m = object(value, 'Model snapshot');
        keys(m, ['name', 'status', 'description', 'entities', 'relationships', 'primitives'], 'Model snapshot');
        validatePersonaOntology({ ...m, schemaVersion: 1, resourceKey: ontology.resourceKey, version: ontology.version });
        if (Boolean(m.primitives?.includes('Source')) !== Boolean(ontology.primitives?.includes('Source')))
            fail('Model variants must preserve the Source primitive.');
    };
    const term = (value, entity = false) => {
        const t = object(value, 'Term');
        keys(t, entity ? ['label', 'description', 'attributes'] : ['label', 'description'], 'Term');
        text(t.label, 'term label', 200);
        text(t.description, 'term description');
        if (entity && t.attributes !== undefined)
            for (const [key, v] of Object.entries(object(t.attributes, 'Attribute terms'))) {
                if (!identifier(key))
                    fail('Invalid attribute term key.');
                term(v);
            }
    };
    const copy = (value) => {
        const c = object(value, 'Copy');
        keys(c, ['label', 'name', 'description', 'glossary', 'entities', 'relationships'], 'Copy');
        text(c.name, 'localized name', 120);
        text(c.label, 'label', 200);
        text(c.description, 'localized description');
        if (c.glossary !== undefined && (!Array.isArray(c.glossary) || c.glossary.length > 100 || c.glossary.some((v) => typeof v !== 'string' || !v.trim() || v.length > 200)))
            fail('Use at most 100 short protected terms.');
        for (const field of ['entities', 'relationships'])
            if (c[field] !== undefined) {
                const entries = Object.entries(object(c[field], 'Terms'));
                if (entries.length > 400)
                    fail('Too many ontology terms.');
                for (const [key, v] of entries) {
                    if (!identifier(key))
                        fail('Invalid term key.');
                    term(v, field === 'entities');
                }
            }
    };
    const content = (s) => {
        if (s.defaultLanguage !== undefined)
            lang(s.defaultLanguage);
        if (s.definition !== undefined)
            model(s.definition);
        for (const field of ['translations', 'variants'])
            if (s[field] !== undefined) {
                const entries = Object.entries(object(s[field], field));
                if (entries.length > 100)
                    fail('Use at most 100 language variants.');
                for (const [tag, v] of entries) {
                    lang(tag);
                    if (field === 'translations')
                        copy(v);
                    else {
                        const variant = object(v, 'Language variant');
                        keys(variant, ['definition'], 'Language variant');
                        model(variant.definition);
                    }
                }
            }
    };
    content(l);
    const regions = new Set(), countries = new Set(), audiences = new Set();
    for (const raw of l.regions) {
        const r = object(raw, 'Region');
        keys(r, ['key', 'label', 'countryCodes', 'defaultLanguage', 'definition', 'translations', 'variants'], 'Region');
        if (!scopeKey(r.key) || regions.has(r.key))
            fail('Use unique region keys.');
        regions.add(r.key);
        text(r.label, 'region label', 120);
        if (!r.label)
            fail('Region label required.');
        lang(r.defaultLanguage);
        if (!Array.isArray(r.countryCodes) || !r.countryCodes.length || r.countryCodes.length > 250)
            fail('Declare country codes.');
        for (const code of r.countryCodes) {
            if (typeof code !== 'string' || !/^[A-Z]{2}$/.test(code) || countries.has(code))
                fail('Each uppercase country code belongs to one region.');
            countries.add(code);
        }
        content(r);
    }
    for (const raw of l.personalizations) {
        const p = object(raw, 'Audience');
        keys(p, ['id', 'label', 'regionKey', 'language', 'priority', 'audience', 'defaultLanguage', 'definition', 'translations', 'variants'], 'Audience');
        if (!scopeKey(p.id) || audiences.has(p.id))
            fail('Use unique audience IDs.');
        audiences.add(p.id);
        text(p.label, 'audience label', 120);
        if (!p.label)
            fail('Audience label required.');
        if (p.regionKey !== undefined && !regions.has(p.regionKey))
            fail('Audience region must exist.');
        if (p.language !== undefined)
            lang(p.language);
        if (p.priority !== undefined && (!Number.isInteger(p.priority) || p.priority < 0 || p.priority > 1000))
            fail('Priority must be 0 to 1000.');
        const a = object(p.audience, 'Audience rules');
        if (a.type === 'individual') {
            keys(a, ['type', 'userIds'], 'Audience rules');
            if (!Array.isArray(a.userIds) || !a.userIds.length || a.userIds.length > 100 || a.userIds.some((v) => typeof v !== 'string' || !v || v.length > 128))
                fail('Use authenticated account IDs.');
        }
        else if (a.type === 'icp') {
            keys(a, ['type', 'all'], 'Audience rules');
            if (!Array.isArray(a.all) || !a.all.length || a.all.length > 20)
                fail('Declare 1 to 20 profile conditions.');
            for (const rawRule of a.all) {
                const rule = object(rawRule, 'Profile condition');
                keys(rule, ['questionId', 'oneOf'], 'Profile condition');
                text(rule.questionId, 'question ID', 100);
                if (!rule.questionId || !Array.isArray(rule.oneOf) || !rule.oneOf.length || rule.oneOf.length > 100 || rule.oneOf.some((v) => !['string', 'number', 'boolean'].includes(typeof v) || typeof v === 'number' && !Number.isFinite(v)))
                    fail('Profile rules require scalar answers.');
            }
        }
        else
            fail('Choose individual or icp audience.');
        content(p);
    }
    for (const selection of allOntologySelections(ontology)) {
        const resolved = materializeOntology(ontology, selection);
        const scope = selection.personalizationId ? l.personalizations.find((p) => p.id === selection.personalizationId) : selection.regionKey ? l.regions.find((r) => r.key === selection.regionKey) : l;
        const c = scope?.translations?.[selection.language];
        if (!c)
            continue;
        for (const [key, t] of Object.entries(c.entities || {})) {
            const e = ontologyEntities(resolved.definition).find(e => e.type === key);
            if (!e || Object.keys(t.attributes || {}).some(k => !Object.prototype.hasOwnProperty.call(e.attributes, k)))
                fail('Term refers to an unknown entity or attribute in its scope.');
        }
        if (Object.keys(c.relationships || {}).some(k => !resolved.definition.relationships.some(r => r.type === k)))
            fail('Term refers to an unknown relationship.');
    }
}
/** Full model replacement followed by copy inheritance; never mutates the authored contract. */
const cloneOntology = (value) => JSON.parse(JSON.stringify(value));
exports.cloneOntology = cloneOntology;
function materializeOntology(ontology, selection) {
    const { localization: l, ...base } = ontology;
    let definition = (0, exports.cloneOntology)(base), copy = {};
    const region = l?.regions.find(r => r.key === selection.regionKey), personal = l?.personalizations.find(p => p.id === selection.personalizationId);
    const translated = (entries, fallback) => [selection.language, selection.language.split('-')[0], fallback, l?.sourceLanguage].filter(Boolean).map(tag => entries?.[tag]).find(v => v !== undefined);
    const apply = (scope, fallback) => {
        if (!scope)
            return;
        const model = translated(scope.variants, fallback)?.definition || scope.definition;
        if (model)
            definition = { ...(0, exports.cloneOntology)(model), schemaVersion: 1, resourceKey: ontology.resourceKey, version: ontology.version };
        const next = translated(scope.translations, fallback);
        if (!next)
            return;
        const entities = { ...copy.entities };
        for (const [key, term] of Object.entries(next.entities || {}))
            entities[key] = { ...entities[key], ...term, attributes: { ...entities[key]?.attributes, ...term.attributes } };
        copy = { ...copy, ...(0, exports.cloneOntology)(next), entities, relationships: { ...copy.relationships, ...next.relationships } };
    };
    apply(l, l?.sourceLanguage);
    apply(region, region?.defaultLanguage);
    apply(personal, personal?.defaultLanguage || personal?.language || l?.sourceLanguage);
    // A replacing model can remove inherited terms; these must not appear in consumer responses.
    copy.entities = Object.fromEntries(Object.entries(copy.entities || {}).filter(([key]) => ontologyEntities(definition).some(e => e.type === key)).map(([key, t]) => [key, { ...t, attributes: Object.fromEntries(Object.entries(t.attributes || {}).filter(([field]) => Object.prototype.hasOwnProperty.call(ontologyEntities(definition).find(e => e.type === key).attributes, field))) }]));
    copy.relationships = Object.fromEntries(Object.entries(copy.relationships || {}).filter(([key]) => definition.relationships.some(r => r.type === key)));
    return { definition, copy, selection };
}
function resolveOntology(ontology, locale = {}, audience = { userId: '', answers: {} }) {
    try {
        return materializeOntology(ontology, (0, context_selection_cjs_1.selectPersonaContext)(ontology.localization || {}, locale, audience));
    }
    catch (error) {
        if (error instanceof OntologyError)
            throw error;
        throw new OntologyError('INVALID_ONTOLOGY_CONTEXT', error.message);
    }
}
function ontologyScopeSelection(ontology, scopeId, language) {
    const l = ontology.localization;
    if (scopeId === 'global')
        return { language: (0, context_selection_cjs_1.contextLanguage)(language || l?.sourceLanguage || 'en') };
    const region = scopeId.startsWith('country:') ? l?.regions.find(r => r.key === scopeId.slice(8)) : undefined;
    const personal = scopeId.startsWith('audience:') ? l?.personalizations.find(p => p.id === scopeId.slice(9)) : undefined;
    if (!region && !personal)
        throw new OntologyError('ONTOLOGY_SCOPE_NOT_FOUND', 'The ontology scope no longer exists.');
    return { ...(region ? { regionKey: region.key, countryCode: region.countryCodes[0] } : {}), ...(personal ? { personalizationId: personal.id, regionKey: personal.regionKey, ...(personal.regionKey ? { countryCode: l?.regions.find(r => r.key === personal.regionKey)?.countryCodes[0] } : {}) } : {}), language: (0, context_selection_cjs_1.contextLanguage)(language || personal?.defaultLanguage || personal?.language || region?.defaultLanguage || l?.sourceLanguage || 'en') };
}
function allOntologySelections(ontology) {
    const l = ontology.localization;
    const scopes = [{ language: l?.sourceLanguage || 'en' }, ...(l?.regions || []).map(r => ({ regionKey: r.key, countryCode: r.countryCodes[0], language: r.defaultLanguage })), ...(l?.personalizations || []).flatMap(p => (p.regionKey ? [p.regionKey] : [undefined, ...(l?.regions || []).map(r => r.key)]).map(regionKey => ({ regionKey, personalizationId: p.id, language: p.defaultLanguage || p.language || l?.sourceLanguage || 'en' })))];
    const tags = new Set([l?.sourceLanguage || 'en', ...Object.keys(l?.translations || {}), ...Object.keys(l?.variants || {}), ...(l?.regions || []).flatMap(r => [r.defaultLanguage, ...Object.keys(r.translations || {}), ...Object.keys(r.variants || {})]), ...(l?.personalizations || []).flatMap(p => [p.language || p.defaultLanguage || l?.sourceLanguage || 'en', ...Object.keys(p.translations || {}), ...Object.keys(p.variants || {})])]);
    if (scopes.length * tags.size > 20000)
        fail('Too many ontology contexts; simplify the candidate scopes.');
    return scopes.flatMap(scope => [...new Set([scope.language, ...tags])].map(language => ({ ...scope, language })));
}
function validateOntologyReferenceShape(value) {
    const r = object(value, 'Ontology reference');
    keys(r, ['entityType', 'ontologyVersion', 'recordsPath', 'fields'], 'Ontology reference');
    if (!identifier(r.entityType) || typeof r.recordsPath !== 'string')
        fail('Declare an entity type and recordsPath.');
    if (r.ontologyVersion !== undefined && (typeof r.ontologyVersion !== 'string' || !/^\d+\.\d+\.\d+$/.test(r.ontologyVersion)))
        fail('Invalid ontology version.');
    const fields = object(r.fields, 'Ontology field references');
    if (!Object.keys(fields).length || Object.keys(fields).length > 200)
        fail('Reference 1 to 200 ontology attributes.');
    pointerSegments(r.recordsPath);
    for (const [field, pointer] of Object.entries(fields)) {
        if (!identifier(field))
            fail('Invalid ontology attribute reference.');
        pointerSegments(pointer);
    }
    return r;
}
function validateOntologyReference(ontology, value) {
    const reference = validateOntologyReferenceShape(value);
    if (reference.ontologyVersion && ontology.version !== reference.ontologyVersion)
        throw new OntologyError('ONTOLOGY_VERSION_MISMATCH', 'The feed requires a different persona ontology version.');
    const entity = ontologyEntities(ontology).find(entity => entity.type === reference.entityType);
    if (!entity)
        throw new OntologyError('UNKNOWN_ENTITY_TYPE', 'The persona ontology does not define this entity type.');
    if (Object.keys(reference.fields).some(field => !Object.prototype.hasOwnProperty.call(entity.attributes, field)))
        throw new OntologyError('UNKNOWN_ENTITY_ATTRIBUTE', 'The persona ontology does not define a referenced attribute.');
    return reference;
}
function pointerSegments(value) {
    if (typeof value !== 'string' || value.length > 2000 || value !== '' && !value.startsWith('/') || /~(?![01])/.test(String(value)))
        fail('Use a valid JSON pointer.');
    const parts = value === '' ? [] : value.slice(1).split('/').map(key => key.replace(/~1/g, '/').replace(/~0/g, '~'));
    if (parts.some(key => ['__proto__', 'constructor', 'prototype'].includes(key)))
        fail('Unsafe JSON pointer.');
    return parts;
}
function atPointer(value, path) {
    return pointerSegments(path).reduce((parent, key) => parent && typeof parent === 'object' && Object.prototype.hasOwnProperty.call(parent, key) ? parent[key] : undefined, value);
}
/** Validate a projection without rewriting JSON, coercing types, or persisting instances. */
function validateOntologyOutput(ontology, reference, output) {
    validateOntologyReference(ontology, reference);
    const entity = ontologyEntities(ontology).find(entity => entity.type === reference.entityType);
    const selected = atPointer(output, reference.recordsPath);
    if (selected === undefined)
        throw new OntologyError('ONTOLOGY_OUTPUT_MISMATCH', 'The declared ontology result path is missing.');
    const rows = Array.isArray(selected) ? selected : [selected];
    for (const row of rows)
        for (const [field, path] of Object.entries(reference.fields)) {
            const value = atPointer(row, path);
            const attribute = entity.attributes[field];
            if (value === undefined && !attribute.required)
                continue;
            if (!ontologyAttributeAccepts(attribute, value))
                throw new OntologyError('ONTOLOGY_OUTPUT_MISMATCH', 'Feed JSON does not match its declared ontology attribute types.');
        }
}
